### ISSUE TITLE
Bruh

### ISSUE THREAD

**Issue by ItzSomebody** [helloxdd/License-System-made-for-BSMC#1]
I don't think you understand the definition of a licensing system. A licensing system is a DRM that allows you to individually control each user's copy of a software.

By the way, this is a terrible anti-piracy because I can just hack the handler factory or search for net/java/URL usage.

**Comment by helloxdd** [comment]
bruh

**Comment by ByteCode-DirectLeaks** [comment]
then you can just close the issue lol
